# Generated by Django 4.2.7 on 2025-05-27 10:48

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WeatherData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.IntegerField(validators=[django.core.validators.MinValueValidator(1800), django.core.validators.MaxValueValidator(2100)])),
                ('january', models.FloatField(blank=True, null=True)),
                ('february', models.FloatField(blank=True, null=True)),
                ('march', models.FloatField(blank=True, null=True)),
                ('april', models.FloatField(blank=True, null=True)),
                ('may', models.FloatField(blank=True, null=True)),
                ('june', models.FloatField(blank=True, null=True)),
                ('july', models.FloatField(blank=True, null=True)),
                ('august', models.FloatField(blank=True, null=True)),
                ('september', models.FloatField(blank=True, null=True)),
                ('october', models.FloatField(blank=True, null=True)),
                ('november', models.FloatField(blank=True, null=True)),
                ('december', models.FloatField(blank=True, null=True)),
                ('winter', models.FloatField(blank=True, null=True)),
                ('spring', models.FloatField(blank=True, null=True)),
                ('summer', models.FloatField(blank=True, null=True)),
                ('autumn', models.FloatField(blank=True, null=True)),
                ('annual', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Weather Data',
                'verbose_name_plural': 'Weather Data',
                'ordering': ['year'],
                'unique_together': {('year',)},
            },
        ),
    ]
